import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useState } from "react";
import { AuthStateContext, IAuthState } from "@/lib/state/auth";

export default function App({ Component, pageProps }: AppProps) {
  const [authState, setAuthState] = useState<IAuthState>({
    loggedIn: false,
    customerId: "",
  });
  return (
    <div>
      <Head>
        <title>SwaadSaathi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AuthStateContext.Provider value={{ authState, setAuthState }}>
      <Component {...pageProps} />
      </AuthStateContext.Provider>
    </div>
  )
}
